### ISSUE TITLE
Name for Crowd Fact Check Side Project

### ISSUE THREAD

**Issue by dre-hh** [dre-hh/toolz#1]
1. Suggest name
2. Use 👍  or 👎 
3. PROFIT

**Comment by dre-hh** [comment]
crowdcheck

**Comment by dre-hh** [comment]
true-false

**Comment by dre-hh** [comment]
orly (o really? )

**Comment by dre-hh** [comment]
backfire-effect
http://rationalwiki.org/wiki/Backfire_effect

**Comment by exsemt** [comment]
am benennen wie Domain heist

**Comment by dre-hh** [comment]
backfire.expert

**Comment by dre-hh** [comment]
fact.io 

ist noch frei

**Comment by dre-hh** [comment]
prooflink.click

20 eur im Jahr

**Comment by dpisarewski** [comment]
trytoprove.it
